language: python
env:
  - SUBLIME_TEXT_VERSION="2"
  - SUBLIME_TEXT_VERSION="3"
matrix:
  include:
    - python: 3.3
      dist: trusty

install:
  # Install Sublime Text and output version
  - curl -L https://rawgit.com/twolfson/sublime-installer/0.2.2/install.sh | sh -s "$SUBLIME_TEXT_VERSION"
  - subl --version

  # Install dependencies
  - pip install -r requirements.txt

before_script:
  # Generate a screen buffer to collect Sublime Text window
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Ensure the scripts self-terminate
  - export SUBLIME_AUTO_KILL=TRUE

script:
  # Run our tests
  - ./test.sh

notifications:
  email: false